/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ritocoin_aw_core_BRCoreTransaction */

#ifndef _Included_org_ritocoin_aw_core_BRCoreTransaction
#define _Included_org_ritocoin_aw_core_BRCoreTransaction
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ritocoin_aw_core_BRCoreTransaction_JNI_COPIES_TRANSACTIONS
#define org_ritocoin_aw_core_BRCoreTransaction_JNI_COPIES_TRANSACTIONS 1L
/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getHash
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getHash
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getVersion
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getInputs
 * Signature: ()[Lorg/ritocoin/aw/core/BRCoreTransactionInput;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getInputs
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getOutputs
 * Signature: ()[Lorg/ritocoin/aw/core/BRCoreTransactionOutput;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getOutputs
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getLockTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getLockTime
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    setLockTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_setLockTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getBlockHeight
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getBlockHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getTimestamp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getTimestamp
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    setTimestamp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_setTimestamp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    serialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_serialize
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    addInput
 * Signature: (Lorg/ritocoin/aw/core/BRCoreTransactionInput;)V
 */
JNIEXPORT void JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_addInput
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    addOutput
 * Signature: (Lorg/ritocoin/aw/core/BRCoreTransactionOutput;)V
 */
JNIEXPORT void JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_addOutput
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    shuffleOutputs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_shuffleOutputs
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getSize
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getStandardFee
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getStandardFee
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    isSigned
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_isSigned
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    sign
 * Signature: ([Lorg/ritocoin/aw/core/BRCoreKey;I)V
 */
JNIEXPORT void JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_sign__Lorg_ritocoin_aw_core_BRCoreKey_3_093_2I
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    isStandard
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_isStandard
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getReverseHash
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getReverseHash
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    getMinOutputAmount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_getMinOutputAmount
  (JNIEnv *, jclass);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_disposeNative
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_initializeNative
  (JNIEnv *, jclass);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    createJniCoreTransaction
 * Signature: ([BJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_createJniCoreTransaction
  (JNIEnv *, jclass, jbyteArray, jlong, jlong);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    createJniCoreTransactionSerialized
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_createJniCoreTransactionSerialized
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_ritocoin_aw_core_BRCoreTransaction
 * Method:    createJniCoreTransactionEmpty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreTransaction_createJniCoreTransactionEmpty
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
