/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ritocoin_aw_core_BRCoreChainParams */

#ifndef _Included_org_ritocoin_aw_core_BRCoreChainParams
#define _Included_org_ritocoin_aw_core_BRCoreChainParams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ritocoin_aw_core_BRCoreChainParams
 * Method:    getJniMagicNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ritocoin_aw_core_BRCoreChainParams_getJniMagicNumber
  (JNIEnv *, jobject);

/*
 * Class:     org_ritocoin_aw_core_BRCoreChainParams
 * Method:    createJniMainnetChainParams
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreChainParams_createJniMainnetChainParams
  (JNIEnv *, jclass);

/*
 * Class:     org_ritocoin_aw_core_BRCoreChainParams
 * Method:    createJniTestnetChainParams
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ritocoin_aw_core_BRCoreChainParams_createJniTestnetChainParams
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
